channels:
  - conda-forge
dependencies:
  - cmake >=3.22
  - cudatoolkit 11.8.*
  - gxx_linux-64 10.3.*
  - make
  - nvcc_linux-64 11.8
  - sysroot_linux-64 2.17
  - mkl-devel
  - pybind11
  - python 3.10.*
