channels:
  - conda-forge
  - nvidia/label/cuda-11.8.0
dependencies:
  - cmake >=3.22
  - cuda-nvcc
  - cuda-libraries-dev
  - gxx_linux-64 10.3.*
  - make
  - sysroot_linux-64 2.17
  - mkl-devel
  - pybind11
  - python 3.10.*
