name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Run every Sunday at midnight
    - cron:  '0 0 * * 0'

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:

          # Oldest supported versions
          - name: Linux (CUDA 10.2)
            cuda: "10.2.89"
            gcc: "8.5.*"
            nvcc: "10.2"

          # Latest supported versions
          - name: Linux (CUDA 11.8)
            cuda: "11.8.0"
            gcc: "10.3.*"
            nvcc: "11.8"

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Install CUDA Toolkit
      uses: Jimver/cuda-toolkit@v0.2.10
      with:
        cuda: ${{ matrix.cuda }}
        linux-local-args: '["--toolkit", "--override"]' 

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: ""
        auto-activate-base: true
        miniforge-variant: Mambaforge

    - name: Prepare dependencies (with CUDA)
      run: |
        sed -i -e "/cudatoolkit/c\  - cudatoolkit ${{ matrix.cuda }}" \
               -e "/gxx_linux-64/c\  - gxx_linux-64 ${{ matrix.gcc }}" \
               -e "/nvcc_linux-64/c\  - nvcc_linux-64 ${{ matrix.nvcc }}" \
               environment.yml

    - name: Show dependency file
      run: cat environment.yml

    - name: Install dependencies
      run: mamba env create -n uammd -f environment.yml
      env:
        CONDA_OVERRIDE_CUDA: ${{ matrix.nvcc }}

    - name: List conda environment
      run: |
        conda activate uammd
        conda list

    - name: Configure, compile, and install
      run: |
        conda activate uammd
        mkdir build && cd build
        cmake .. \
              -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
